### PR TITLE
Fix Str::squish() signature

### LINKED ISSUE #5: Str::squish(string $string): string must be compatible
In the latest Laravel version, you contributed #41791. Since the method signature is different to `Str::squish()` used in this package, it's broken.

https://flareapp.io/share/xPQ0JYDm/claim/gXBBRjjurpDfj1Jmh5snDPF3LR8DvqVy#share

### PR DESCRIPTION
**Pull request by danharrin**
Fixes #5.

### CODE REVIEW

**Comment by dwightwatson** [comment]
Could we just remove the entire method? It's basically the same implementation so it should work just as expected I think.

**Comment by dwightwatson** [comment]
Actually I'll just merge this for now so you can have it work with dev-master. Won't be able to tag a release straight away as I'm not at a computer.

**Comment by dwightwatson** [comment]
Appreciate your help finding this and sorting it out!

**Comment by danharrin** [comment]
> Could we just remove the entire method? It's basically the same implementation so it should work just as expected I think.

I didn't do that because we need to maintain L8 compatibility, right?

**Comment by dwightwatson** [comment]
Good point. Maybe I'll prep a release to drop Laravel 8 support just to avoid any inconsistencies.

**Pull request merged**
